### ISSUE TITLE
Ply Parsing fails

### ISSUE THREAD

**Issue by dzeitman** [laanlabs/metal-splats#1]
Running Xcode 15 Beta -8 - target iOS 17 

Taping any of the models.  

Error: Line 115: SplatSimpleView.swift:
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: MetalSplat.SplatError.plyParsingFailed

Can you be more specific on the tooling and device requirements for getting this running?

Xcode version
Deploy target version
Device OS version

**Comment by cclaan** [comment]
Can you confirm the ply files exist and are large files ~80mb . You may need to run 'git lfs pull' to download them. If it's another issue can you give a stacktrace. Thanks

**Comment by dzeitman** [comment]
Closing - my bad the ply models needed to be pulled.

**Comment by dzeitman** [comment]
Working as expected.  Phenominal!
