### ISSUE TITLE
'SplatCloudC.h' file not found

### ISSUE THREAD

**Issue by zxwzxw** [laanlabs/metal-splats#4]
failed to emit precompiled header '/Users/mofine_zjh/Library/Developer/Xcode/DerivedData/MetalSplat-arqhugkuphwgbuhlbzijmnjdjlps/Build/Intermediates.noindex/PrecompiledHeaders/BridgingHeader-swift_2NVJ7LK4I2QKF-clang_197ZI01TTIAC0.pch' for bridging header '/Users/mofine_zjh/Downloads/metal-splats-main/MetalSplat/BridgingHeader.h'

**Comment by cclaan** [comment]
Forgot to remove that, the file is not currently used in main branch. Should work now
